### ISSUE TITLE
w7 1.f) Warnings

### ISSUE THREAD

**Issue by dagruneir** [ITU-BDSA23-GROUP14/Chirp#87]
### Overview
We need all warnings to be addressed

### User story
As a developer, I want my code to build with no warnings

### Acceptance criteria
* All warnings in the code have been addressed

### Full task description
Ensure that your project builds without any warnings. That is, make sure that all warnings in your code are addressed.

**Comment by Mardesol** [comment]
There are no warnings - we good!
