### ISSUE TITLE
w7 1.d) Command Query Separation

### ISSUE THREAD

**Issue by dagruneir** [ITU-BDSA23-GROUP14/Chirp#88]
### Overview
Seperate commands from queries so no method is both

### User story
As a developer, I want all my method to serve one function, either being a command or a query

### Acceptance criteria
* No method is both a Command and a Query

### Full task description
Ensure that the methods that are exposed in your repositories follow are separated into commands and queries:

> Separate Commands from Queries. Commands are procedures that have side effects. Queries are functions that return data. Every method should be either a Command or a Query, but not both.<font size=3>
Source: Mark Seemann <i>"Code That Fits in Your Head"</i>
</font>

**Comment by Mardesol** [comment]
We went through the source code together and agreed that there was proper CQS
